ll-nd: ll-nd.o linked-list.o
	gcc ll-nd.o linked-list.o -o ll-nd

ll-nd.o: ll-nd.c ll-nd.h
	gcc -c ll-nd.c -ggdb

linked-list.o: ../double/linked-list.c ../double/linked-list.h
	gcc -c ../double/linked-list.c -ggdb
